id: I2EE8A0D1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T11:28:58+00:00'
last_modified: '2022-06-07T12:29:40.398466+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4PD759
  title: གསུང་འབུམ། བསྟན་པའི་དབང་ཕྱུག
  author: ''
  base:
    4E8B:
      image_group_id: I4PD899
      title: ''
      total_pages: 754
      order: 1
      base_file: 4E8B.txt
    2D6B:
      image_group_id: I4PD900
      title: ''
      total_pages: 678
      order: 2
      base_file: 2D6B.txt
    F3AE:
      image_group_id: I4PD901
      title: ''
      total_pages: 660
      order: 3
      base_file: F3AE.txt
    F640:
      image_group_id: I4PD902
      title: ''
      total_pages: 658
      order: 4
      base_file: F640.txt
    F01B:
      image_group_id: I4PD903
      title: ''
      total_pages: 644
      order: 5
      base_file: F01B.txt
    BFBA:
      image_group_id: I4PD904
      title: ''
      total_pages: 712
      order: 6
      base_file: BFBA.txt
    C3F9:
      image_group_id: I4PD905
      title: ''
      total_pages: 512
      order: 7
      base_file: C3F9.txt
    ED49:
      image_group_id: I4PD906
      title: ''
      total_pages: 546
      order: 8
      base_file: ED49.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
