id: I2EE8A0D1
legacy_id: P000625
ocr_import_info:
  bdrc_scan_id: W4PD759
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T11:25:08'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T02:51:58.702188+00:00'
last_modified: 2022-09-04 10:53:42.539425
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4PD759
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW4PD759
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བསྟན་པའི་དབང་ཕྱུག
  author: ཁང་སར་བསྟན་པའི་དབང་ཕྱུག
statistics:
  ocr_word_mean_confidence_index: 0.9365452620445098
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I4PD901:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD901
      total_pages: 660
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I4PD901.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9352839844906242
    legacy_id: v003
  I4PD902:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD902
      total_pages: 658
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I4PD902.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9258132807967584
    legacy_id: v004
  I4PD906:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD906
      total_pages: 546
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I4PD906.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9502219957970949
    legacy_id: v008
  I4PD900:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD900
      total_pages: 678
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I4PD900.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9259101451246251
    legacy_id: v002
  I4PD899:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD899
      total_pages: 754
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4PD899.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9410146027144735
    legacy_id: v001
  I4PD905:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD905
      total_pages: 512
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I4PD905.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9426468243901153
    legacy_id: v007
  I4PD903:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD903
      total_pages: 644
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I4PD903.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.934958084218397
    legacy_id: v005
  I4PD904:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD904
      total_pages: 712
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I4PD904.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9405168626814752
    legacy_id: v006
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
