id: P000625
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W4PD759
  title: གསུང་འབུམ། བསྟན་པའི་དབང་ཕྱུག
  author: ''
  volumes:
    263afb050f474f1f84762fa993c03686:
      image_group_id: I4PD899
      title: ''
      volume_number: 1
      total_pages: 754
    5620ef706b474722812f032c37c1ae3f:
      image_group_id: I4PD900
      title: ''
      volume_number: 2
      total_pages: 678
    f723fccef0d3402382d00c58e45abe23:
      image_group_id: I4PD901
      title: ''
      volume_number: 3
      total_pages: 660
    aef1c60d7d8148d987a514ab5301a585:
      image_group_id: I4PD902
      title: ''
      volume_number: 4
      total_pages: 658
    51d34b7d7beb44a3be828a246e320d3a:
      image_group_id: I4PD903
      title: ''
      volume_number: 5
      total_pages: 644
    f49c75d3abd841808468d76d04be0b2a:
      image_group_id: I4PD904
      title: ''
      volume_number: 6
      total_pages: 712
    c6f57a99866242f0b0b1faf2453539d1:
      image_group_id: I4PD905
      title: ''
      volume_number: 7
      total_pages: 512
    8a0eeddadf184dc087198e2574cc1665:
      image_group_id: I4PD906
      title: ''
      volume_number: 8
      total_pages: 546
